### ISSUE TITLE
Question, is there a way to limit the number of pages in the page numbers selection

### ISSUE THREAD

**Issue by liranp1** [wikiti/jquery-paginate#1]
i have a table with more then 1000 rows.
i limit the results to 15 result per page.
but in the pages numbers i see 1-70 that is allot, is there a way to display only few and add ' ...'
so user will know there is more?

**Comment by EFinish** [comment]
Look at https://github.com/wikiti/jquery-paginate#advanced-options at the 'limit' option. The example right below it uses limit to only show 10 results per page.

**Comment by khe817** [comment]
@EFinish That did not answer @liranp1 's question. I have the same question as @liranp1 too.

I did a small trick for displaying page numbers within the n+-3 range of current select page:

```javascript

$(document).ready(function() {
    $('#acc-invoice-list').paginate({
        limit: 10,
        onCreate: function(obj) {prettyPagination(3);},
        onSelect: function(obj, i) {prettyPagination(i+1);}
    });

});

function prettyPagination(currentPageIndex) {
    $('.page-navigation a').css('display', 'none');
    $('.page-navigation a').slice((currentPageIndex-3) <0 ? 0 : currentPageIndex-2, currentPageIndex).css('display', 'inline-block');
    $('.page-navigation a').slice(currentPageIndex, currentPageIndex+4).css('display', 'inline-block');
    // always display previous & next navigations
    $('.page-navigation a').slice(0, 2).css('display', 'inline-block');
    $('.page-navigation a').slice(-3, -1).css('display', 'inline-block');
    $('.page-navigation a').last().css('display', 'inline-block');
}
```

**Comment by EFinish** [comment]
@khe817 I am mistaken. Thank you for correcting me.

**Comment by liranp1** [comment]
thank you all for your help!
i works amazing

**Comment by GirishaVil** [comment]
how to count number of records per page in this?

**Comment by wikiti** [comment]
Hey all!

Please, take a look at [this comment](https://github.com/wikiti/jquery-paginate/issues/3#issuecomment-377718555).

Best regards,
Daniel
