### ISSUE TITLE
Pagination not working in IE 11 

### ISSUE THREAD

**Issue by Pgarg09** [wikiti/jquery-paginate#4]
@wikiti 
When trying to execute .paginate. Debug showing , property is not allowed .
 $('#txyz').paginate({
	    limit: 10
});

**Comment by Pgarg09** [comment]
Hello @wikiti : Any update to this.
Thanks :)

**Comment by wikiti** [comment]
Hello @Pgarg09!

I'll take a look at it once I've some spare time.


Best regards,
Daniel

**Comment by Pgarg09** [comment]
@wikiti 
Thanks for the reply.
Its seems that js file for paginate is getting loaded in chrome but not in IE 11.

**Comment by Pgarg09** [comment]
@wikiti :+1: 
Issue can be closed. Code is perfectly fine. It was compatibility issue which is working fine now on IE 11.
Thanks for the support :)
